# Generated by Django 4.2.6 on 2023-10-31 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('title', models.CharField(max_length=1200)),
                ('description', models.TextField()),
                ('views', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=520)),
                ('minititle', models.CharField(max_length=520)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=340)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('name', models.CharField(max_length=200)),
                ('price', models.SmallIntegerField()),
                ('discount_price', models.SmallIntegerField()),
                ('stock', models.BooleanField(default=True)),
                ('weight', models.CharField(max_length=220)),
                ('lifetime', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('information', models.TextField()),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoapp.brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoapp.category')),
                ('wishlist', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terkib', to='ecoapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Basket_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
