# Generated by Django 4.2.7 on 2023-11-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0009_blog_category_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='subject',
        ),
    ]
