# Generated by Django 4.2.7 on 2023-11-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0011_partners_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.CharField(blank=True, max_length=2050, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='partners',
            name='link',
        ),
    ]
